// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9EPSP_doFspnwZePK3U0JJaBHtB4tM-k',
    appId: '1:476355462642:web:8a951d6b43f5436f6f576b',
    messagingSenderId: '476355462642',
    projectId: 'chatapp-d71a7',
    authDomain: 'chatapp-d71a7.firebaseapp.com',
    storageBucket: 'chatapp-d71a7.appspot.com',
    measurementId: 'G-9FKE7073H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2cp3Z4VC_hx20Gz3bcF8heIHL0HzoHio',
    appId: '1:476355462642:android:5f95fa2f70f9eb386f576b',
    messagingSenderId: '476355462642',
    projectId: 'chatapp-d71a7',
    storageBucket: 'chatapp-d71a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5TpYtwZCV_C-6_68xhPdUGu5KI8eTxJs',
    appId: '1:476355462642:ios:5ea3768c8d2512926f576b',
    messagingSenderId: '476355462642',
    projectId: 'chatapp-d71a7',
    storageBucket: 'chatapp-d71a7.appspot.com',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5TpYtwZCV_C-6_68xhPdUGu5KI8eTxJs',
    appId: '1:476355462642:ios:1fed7164f25d71d46f576b',
    messagingSenderId: '476355462642',
    projectId: 'chatapp-d71a7',
    storageBucket: 'chatapp-d71a7.appspot.com',
    iosBundleId: 'com.example.newChatApp.RunnerTests',
  );
}
